---
build_from:
  aarch64: docker.io/node:22.9.0-alpine3.20
  amd64: docker.io/node:22.9.0-alpine3.20
  armv7: docker.io/node:22.9.0-alpine3.20
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
